# Input/output configuration
input_dir: /scratch/data/exatrkx/train_100_events
output_dir: ./out/hitgraphs_100_5GeV
n_files: 100

# Graph building configuration
selection:
    pt_min: 5. # GeV
    phi_slope_max: 0.000262
    z0_max: 15000
    n_phi_sections: 1
    n_eta_sections: 1
    eta_range: [-5, 5]
